// Generated by CoffeeScript 1.4.0

!(function(context, definition) {
  if ('function' === typeof require && typeof exports === typeof module) {
    return module.exports = definition;
  }
  return context['async'] = definition;
})(this, (function() {
  var a, _callback, _static;
  a = function async(beginning_result) {
    if (typeof this.serial === 'undefined') {
      return new a(arguments[0]);
    }
    this.a = [];
    this.beginning_result = beginning_result;
    this.beginning_length = 0;
    this.processed = 0;
  };;
  a.prototype._apply = function(args) {
    if (this.a.length) {
      return (args[0] ? this.a.splice(0, this.a.length).shift() : this.a[this.a.length - 1]).apply({}, args);
    }
  };
  a.prototype._next = function(parallel) {
    var _this = this;
    return function() {
      _this.processed++;
      if (arguments[0]) {
        return _this._apply(arguments);
      }
      console.log(arguments);
      _this.afterEach_callback.apply(_this._next(!_this.afterEach_callback.length), arguments);
      if (!parallel || _this.processed === _this.beginning_length) {
        while (_this._apply(arguments) && parallel) {}
      }
    };
  };
  a.prototype._push = function(args, parallel) {
    var dont_end, key, task, _fn,
      _this = this;
    task = args[0];
    '[object Function]' === Object.prototype.toString.call(task) && (dont_end = task = [task]);
    _fn = function(cb, parallel) {
      _this.beginning_length++;
      return _this.a.push(function() {
        var next;
        _this.a.pop();
        _this.beforeEach_callback.apply(_this._next(!_this.beforeEach_callback.length), arguments);
        args = Array.prototype.slice.apply(arguments).slice(1);
        cb.apply((next = _this._next(parallel)), args.concat(next));
        return parallel && (1 === _this.a.length || !!_this._apply(arguments));
      });
    };
    for (key in task) {
      _fn(task[key], parallel === null ? !task[key].length : parallel);
    }
    return (dont_end ? this : this.end(typeof args[1] === 'function' ? args[1] : function() {}));
  };
  a.prototype.end = a.prototype["finally"] = a.prototype.ensure = a.prototype.afterAll = a.prototype.after = a.prototype.complete = a.prototype.done = function(cb) {
    var _this = this;
    this.a.push(function() {
      (!!arguments[0] && (_this.error_callback.apply(_this._next(!_this.error_callback.length), arguments))) || (_this.success_callback.apply(_this._next(!_this.success_callback.length), arguments));
      return cb.apply({}, arguments);
    });
    this.a.reverse();
    (this.begin_callback = this.begin_callback || function() {}) && (this.beforeAll_callback = this.beforeAll_callback || function() {}) && (this.beforeEach_callback = this.beforeEach_callback || function() {}) && (this.afterEach_callback = this.afterEach_callback || function() {}) && (this.error_callback = this.error_callback || function() {}) && (this.success_callback = this.success_callback || function() {});
    this.beforeAll_callback.apply(this._next(!this.beforeAll_callback.length), arguments);
    this._apply((typeof this.beginning_result)[0] === 'u' ? [null] : [null, this.beginning_result]);
    return this;
  };
  a.prototype.serial = a.prototype.series = a.prototype.blocking = a.prototype.waterfall = function() {
    return this._push(arguments, false);
  };
  a.prototype.parallel = a.prototype.nonblocking = function() {
    return this._push(arguments, true);
  };
  a.prototype["do"] = a.prototype.then = a.prototype.auto = function() {
    return this._push(arguments, null);
  };
  (_callback = function(func) {
    return function(cb) {
      this[func + '_callback'] = cb;
      return this;
    };
  }) && (a.prototype.begin = a.prototype["try"] = a.prototype["new"] = a.prototype.flow = _callback('begin')) && (a.prototype.beforeAll = a.prototype.before = _callback('beforeAll')) && (a.prototype.beforeEach = _callback('beforeEach')) && (a.prototype.afterEach = a.prototype.between = a.prototype.inbetween = _callback('afterEach')) && (a.prototype.error = a.prototype["catch"] = a.prototype.rescue = _callback('error')) && (a.prototype.success = a.prototype["else"] = _callback('success'));
  (_static = function(func) {
    return function() {
      var b;
      return (b = new a)[func].apply(b, arguments);
    };
  }) && (a.serial = a.series = a.blocking = a.waterfall = _static('serial')) && (a.parallel = a.nonblocking = _static('parallel')) && (a["do"] = a.then = a.auto = _static('do')) && (a.end = a["finally"] = a.ensure = a.afterAll = a.after = a.complete = a.done = _static('end')) && (a.begin = a["try"] = a["new"] = a.flow = _static('begin')) && (a.beforeAll = a.before = _static('beforeAll')) && (a.beforeEach = _static('beforeEach')) && (a.afterEach = a.between = a.inbetween = _static('afterEach')) && (a.error = a["catch"] = a.rescue = _static('error')) && (a.success = a["else"] = _static('success'));
  a.whilst = function(test, iterator, cb) {
    var _this = this;
    (test() && iterator(function(err) {
      return (!!err && cb(err)) || _this.whilst(test, iterator, cb);
    })) || cb();
  };
  return a;
})());
